### ISSUE TITLE
TODO: Begriffsentwicklung

### ISSUE THREAD

**Issue by krugbuild** [krugbuild/wiki-pop-quelle#2]
Abgleich von Peak-Parallelen via Wortentwicklung.

**Comment by Soe-Ra** [comment]
06.2013-31.12.2017
Es scheint eine paralle zwischen der Auswertung der Wikipedia Versionsgeschichte sowie in der Analyse des ZEIT Corpos für das Lemma "Populismus" im Zeitraum zwischen 2013 und 2017 zu geben.
Im folgenden sollen unter der Zuhilfenahme von DiaCollo Begriffsgruppen gebildet werden.

**Comment by Soe-Ra** [comment]
Im folgenden müssen noch die Bezeichnungen der Analyse nachvollzogen werden.

**Comment by Soe-Ra** [comment]
Die meisten unklaren Begriffe konnten geklärt werden.
